// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReadmeGen;

internal sealed partial class Vsix {
    public const string Id = "ReadmeGen.3758e512-f340-4971-8626-5fd073db7cae";
    public const string Name = "ReadmeGen";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Tim Heuer";
    public const string Tags = "";
}
