// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReadmeGen;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids {
    public const string ReadmeGenString = "8d5f12ed-e847-4244-8ba8-8fc627829335";
    public static Guid ReadmeGen = new Guid(ReadmeGenString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds {
    public const int MyMenuGroup = 0x0001;
    public const int MyCommand = 0x0100;
}